syntax = "proto3";

package auth.v1;

service AuthService {
    rpc Register(RegisterRequest) returns (AuthResponse);
    rpc Login(LoginRequest) returns (AuthResponse);
    rpc Refresh(RefreshRequest) returns (AuthResponse);
    rpc Logout(LogoutRequest) returns (LogoutResponse);

    rpc ValidateAccessToken(ValidateAccessTokenRequest) returns (ValidateAccessTokenResponse);
}


//Register flow
message RegisterRequest {
    string email = 1;
    string password = 2;
    string name = 3;
}
//Login flow
message LoginRequest {
    string email = 1;
    string password = 2;
}
//Logout flow
message LogoutRequest {
  string refresh_token = 1;
}
message LogoutResponse {
  bool success = 1;
}


//Tokens flow
message RefreshRequest {
    string refresh_token = 1;
}
message ValidateAccessTokenRequest {
    string access_token = 1;
}
message ValidateAccessTokenResponse {
  bool valid = 1;
  UserPayload user = 2;
}


//shared
message AuthResponse {
    string access_token = 1;
    string refresh_token = 2;
    UserPayload user = 3;
}
message UserPayload {
  string id = 1;
  string email = 2;
  string name = 3;
}